/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.2 at Fri Apr 17 15:16:48 2020. */

#include "RegisterFaceIdWithPicParams.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t RegisterFaceIdWithPicParams_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, RegisterFaceIdWithPicParams, faceName, faceName, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, RegisterFaceIdWithPicParams, filePath, faceName, 0),
    PB_LAST_FIELD
};

const pb_field_t RegisterFaceIdFromCameraParams_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, RegisterFaceIdFromCameraParams, faceName, faceName, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, RegisterFaceIdFromCameraParams, timeoutMs, faceName, 0),
    PB_LAST_FIELD
};

const pb_field_t RegisterFaceIdWithTraceIdParams_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, RegisterFaceIdWithTraceIdParams, faceName, faceName, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, RegisterFaceIdWithTraceIdParams, traceId, faceName, 0),
    PB_LAST_FIELD
};

const pb_field_t SetFaceIdParams_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SetFaceIdParams, faceId, faceId, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, SetFaceIdParams, faceName, faceId, 0),
    PB_LAST_FIELD
};

const pb_field_t ListFaceIdParams_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, ListFaceIdParams, start, start, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, ListFaceIdParams, length, start, 0),
    PB_LAST_FIELD
};

const pb_field_t FaceIdInfo_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, FaceIdInfo, faceId, faceId, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, FaceIdInfo, faceName, faceId, 0),
    PB_LAST_FIELD
};

const pb_field_t FaceIdListData_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, FaceIdListData, start, start, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, FaceIdListData, faces, start, &FaceIdInfo_fields),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
